brainforces/brainforces/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.staticfiles.urls
import django.urls
import django.utils.timezone
import django.views.generic

import core.views


urlpatterns = [
    django.urls.path('', django.urls.include('homepage.urls')),
    django.urls.path('archive/', django.urls.include('archive.urls')),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path('auth/', django.urls.include('users.urls')),
    django.urls.path('auth/', django.urls.include('django.contrib.auth.urls')),
    django.urls.path('quizzes/', django.urls.include('quiz.urls')),
    django.urls.path(
        'ckeditor/', django.urls.include('ckeditor_uploader.urls')
    ),
    django.urls.path(
        'organizations/', django.urls.include('organization.urls')
    ),
    django.urls.path('about/', django.urls.include('about.urls')),
    django.urls.path(
        'social-auth/',
        django.urls.include('social_django.urls', namespace='social_auth'),
    ),
]

handler404 = core.views.custom_404
handler500 = core.views.custom_500


if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include('debug_toolbar.urls')
        ),
    )
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    else:
        urlpatterns += (
            django.contrib.staticfiles.urls.staticfiles_urlpatterns()
        )

brainforces/organization/urls.py
import django.urls

import organization.views


app_name = 'organization'

urlpatterns = [
    django.urls.path(
        '<int:pk>/',
        organization.views.OrganizationMainView.as_view(),
        name='profile',
    ),
    django.urls.path(
        '<int:pk>/users/',
        organization.views.OrganizationUsersView.as_view(),
        name='users',
    ),
    django.urls.path(
        '<int:pk>/join/',
        organization.views.JoinOrganizationView.as_view(),
        name='join',
    ),
    django.urls.path(
        '<int:pk>/quizzes/',
        organization.views.OrganizationQuizzesView.as_view(),
        name='quizzes',
    ),
    django.urls.path(
        '<int:pk>/users/<int:user_pk>/delete/',
        organization.views.DeleteUserFromOrganizationView.as_view(),
        name='delete_user',
    ),
    django.urls.path(
        '<int:pk>/users/<int:user_pk>/update/<int:new_role>/',
        organization.views.UpdateUserOrganizationRoleView.as_view(),
        name='update_user_role',
    ),
    django.urls.path(
        '',
        organization.views.OrganizationListView.as_view(),
        name='list',
    ),
    django.urls.path(
        '<int:pk>/posts/',
        organization.views.OrganizationPostsView.as_view(),
        name='posts',
    ),
    django.urls.path(
        '<int:pk>/posts/<int:post_pk>/',
        organization.views.PostCommentsView.as_view(),
        name='post_detail',
    ),
    django.urls.path(
        '<int:pk>/posts/<int:post_pk>/like/',
        organization.views.CreateLikeView.as_view(),
        name='like_post',
    ),
    django.urls.path(
        '<int:pk>/create_quiz/',
        organization.views.QuizCreateView.as_view(),
        name='create_quiz',
    ),
    django.urls.path(
        '<int:pk>/create_post/',
        organization.views.CreatePostView.as_view(),
        name='create_post',
    ),
]

brainforces/quiz/urls.py
import django.urls

import quiz.views


app_name = 'quiz'

urlpatterns = [
    django.urls.path('', quiz.views.QuizListView.as_view(), name='list'),
    django.urls.path(
        '<int:pk>/',
        quiz.views.QuizDetailView.as_view(),
        name='quiz_detail',
    ),
    django.urls.path(
        '<int:pk>/user_answers/',
        quiz.views.UserAnswersList.as_view(),
        name='user_answers_list',
    ),
    django.urls.path(
        '<int:pk>/questions/<int:question_pk>/',
        quiz.views.QuestionDetailView.as_view(),
        name='question_detail',
    ),
    django.urls.path(
        '<int:pk>/standings/',
        quiz.views.StandingsList.as_view(),
        name='standings_list',
    ),
    django.urls.path(
        '<int:pk>/questions/',
        quiz.views.QuestionsView.as_view(),
        name='questions',
    ),
    django.urls.path(
        '<int:pk>/register/',
        quiz.views.QuizRegistrationView.as_view(),
        name='register',
    ),
    django.urls.path(
        '<int:pk>/make_results/',
        quiz.views.MakeQuizResultsView.as_view(),
        name='make_results',
    ),
]

brainforces/users/urls.py
import django.contrib.auth.views
import django.urls

import users.forms
import users.views


app_name = 'users'

urlpatterns = [
    django.urls.path(
        'login/',
        django.contrib.auth.views.LoginView.as_view(
            template_name='users/login.html',
            form_class=users.forms.CustomAuthenticationForm,
        ),
        name='login',
    ),
    django.urls.path(
        'logout/',
        django.contrib.auth.views.LogoutView.as_view(
            template_name='users/logout.html'
        ),
        name='logout',
    ),
    django.urls.path(
        'password_change/',
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            form_class=users.forms.CustomPasswordChangeForm,
        ),
        name='password_change',
    ),
    django.urls.path(
        'password_change/done/',
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    django.urls.path(
        'password_reset/',
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            form_class=users.forms.CustomPasswordResetForm,
        ),
        name='password_reset',
    ),
    django.urls.path(
        'password_reset/done/',
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    django.urls.path(
        'reset/<uidb64>/<token>/',
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            form_class=users.forms.CustomSetPasswordForm,
        ),
        name='password_reset_confirm',
    ),
    django.urls.path(
        'reset/done/',
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    django.urls.path(
        'signup/', users.views.SignupView.as_view(), name='signup'
    ),
    django.urls.path(
        'activate/<uidb64>/<token>/',
        users.views.ActivateUserView.as_view(),
        name='activate_user',
    ),
    django.urls.path(
        '<int:pk>/',
        users.views.UserProfileView.as_view(),
        name='profile',
    ),
    django.urls.path(
        '<int:pk>/change/',
        users.views.UserProfileChangeView.as_view(),
        name='profile_change',
    ),
    django.urls.path(
        'users/',
        users.views.UserListView.as_view(),
        name='list',
    ),
    django.urls.path(
        'reset_login_attempts/<uidb64>/<token>/',
        users.views.ResetLoginAttemptsView.as_view(),
        name='reset_login_attempts',
    ),
    django.urls.path(
        '<int:pk>/answers/',
        users.views.UserAnswersView.as_view(),
        name='answers',
    ),
    django.urls.path(
        '<int:pk>/quizzes/',
        users.views.UserQuizzesView.as_view(),
        name='quizzes',
    ),
    django.urls.path(
        '<int:pk>/organizations/',
        users.views.UserOrganizationsView.as_view(),
        name='organizations',
    ),
    django.urls.path(
        '<int:pk>/create_organization/',
        users.views.CreateOrganizationView.as_view(),
        name='create_organization',
    ),
]

brainforces/users/models.py
import transliterate

import django.contrib.auth.models
import django.db.models
import django.urls

import core.models
import users.managers


def generate_image_path(obj: django.db.models.Model, filename: str) -> str:
    """генерируем файловый пусть к картинке"""
    filename = transliterate.translit(filename, 'ru', reversed=True)
    return f'users/{obj.user.pk}/{filename}'


class User(django.contrib.auth.models.AbstractUser):
    """кастомный пользователь"""

    objects = users.managers.UserManager()
    email = django.db.models.EmailField(
        verbose_name='почта',
        help_text='Электронная почта пользователя',
        blank=True,
        max_length=100,
        unique=True,
    )
    login_attempts = django.db.models.IntegerField(
        default=0,
        verbose_name='неудачные попытки',
        help_text='Количество неудачных попыток входа в аккаунт',
    )

    class Meta(django.contrib.auth.models.AbstractUser.Meta):
        db_table = 'auth_user'
        swappable = 'AUTH_USER_MODEL'

    def get_absolute_url(self) -> str:
        """путь к user_detail"""
        return django.urls.reverse_lazy(
            'users:profile', kwargs={'pk': self.pk}
        )


class Profile(core.models.AbstractImageModel):
    """профиль пользователя"""

    user = django.db.models.OneToOneField(
        User,
        related_name='profile',
        verbose_name='профиль',
        help_text='Профиль пользователя',
        on_delete=django.db.models.CASCADE,
        blank=True,
        null=True,
    )
    image = django.db.models.ImageField(
        blank=True,
        verbose_name='аватарка',
        help_text='Аватарка пользователя',
        upload_to=generate_image_path,
        null=True,
    )
    rating = django.db.models.PositiveIntegerField(
        verbose_name='рейтинг', help_text='Рейтинг пользователя', default=0
    )

    class Meta:
        verbose_name = 'профиль'
        verbose_name_plural = 'профили'

    def __str__(self) -> str:
        """строковое представление"""
        return f'Профиль пользователя {self.user.pk}'

brainforces/organization/forms.py
import django.core.exceptions
import django.db.models
import django.forms

import organization.models
import users.models


class InviteToOrganizationForm(django.forms.Form):
    """форма приглашения нового пользователя"""

    username = django.forms.CharField(help_text='Имя или почта')

    def clean_username(self) -> str:
        """
        валидируем пользователя: имя или почта
        должны существовать
        """
        username = self.cleaned_data['username']
        user = users.models.User.objects.get_user_by_username_or_email(
            username=username
        )
        if user is None:
            raise django.core.exceptions.ValidationError('Ошибка')
        self.cleaned_data['user_obj'] = user
        return username


class PostForm(django.forms.ModelForm):
    """форма создания поста организации"""

    class Meta:
        model = organization.models.OrganizationPost
        fields = ('name', 'text', 'is_private')

brainforces/users/forms.py
import django.contrib.auth.forms
import django.contrib.auth.tokens
import django.core.exceptions
import django.forms

import organization.models
import users.models
import users.tasks


class SignUpForm(django.contrib.auth.forms.UserCreationForm):
    """форма регистрации"""

    class Meta(django.contrib.auth.forms.UserCreationForm.Meta):
        fields = ('username', 'email', 'password1', 'password2')
        model = users.models.User

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Имя пользователя'
        self.fields['username'].help_text = 'Не более 150 символов. '
        'Только буквы, цифры и символы @/./+/-/_.'

        self.fields['email'].label = 'Почта'
        self.fields['email'].help_text = 'Введите адрес электронной почты'

        self.fields['password1'].label = 'Пароль'
        self.fields['password1'].help_text = 'Придумайте пароль'

        self.fields['password2'].label = 'Пароль еще раз'
        self.fields['password2'].help_text = 'Подтвердите пароль'


class CustomAuthenticationForm(django.contrib.auth.forms.AuthenticationForm):
    """форма авторизации"""

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Имя пользователя'
        self.fields['username'].help_text = 'Введите имя польвователя'

        self.fields['password'].label = 'Пароль'
        self.fields['password'].help_text = 'Введите пароль'


class CustomPasswordChangeForm(django.contrib.auth.forms.PasswordChangeForm):
    """форма смены пароля"""

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['old_password'].label = 'Старый пароль'
        self.fields['old_password'].help_text = 'Введите старый пароль'

        self.fields['new_password1'].label = 'Новый пароль'
        self.fields['new_password1'].help_text = 'Придумайте пароль'

        self.fields['new_password2'].label = 'Пароль еще раз'
        self.fields['new_password2'].help_text = 'Подтвердите пароль'


class CustomPasswordResetForm(django.contrib.auth.forms.PasswordResetForm):
    """форма для отправки письма для восстановления пароля"""

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'Почта'
        self.fields[
            'email'
        ].help_text = 'Введите электронную почту, к которой привязан аккаунт'

    def clean_email(self) -> str:
        """нормализуем почту"""
        email = users.models.User.objects.normalize_email(
            self.cleaned_data['email']
        )
        user_obj = (
            users.models.User.objects.filter(email=email, is_active=True)
            .only('email')
            .first()
        )
        if user_obj:
            return email
        raise django.core.exceptions.ValidationError(
            'Нет пользователя с такой почтой'
        )

    def send_mail(self, *args, **kwargs) -> None:
        """отправка почты для смены пароля"""
        context = args[2]
        token_generator = django.contrib.auth.tokens.default_token_generator
        users.tasks.send_email_with_token.delay(
            user_id=context['user'].pk,
            template_name='users/emails/reset_password.html',
            subject='Восстановление пароля',
            where_to='users:password_reset_confirm',
            domain=context['domain'],
            protocol=context['protocol'],
            token=token_generator.make_token(context['user']),
        )


class CustomSetPasswordForm(django.contrib.auth.forms.SetPasswordForm):
    """форма для нового пароля"""

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].label = 'Новый пароль'
        self.fields['new_password1'].help_text = 'Придумайте пароль'

        self.fields['new_password2'].label = 'Пароль еще раз'
        self.fields['new_password2'].help_text = 'Подтвердите пароль'


class CustomUserChangeForm(django.contrib.auth.forms.UserChangeForm):
    """форма изменения пользователя"""

    password = None

    class Meta:
        model = users.models.User
        fields = ('username', 'first_name', 'last_name')
        labels = {
            'username': 'Имя пользователя',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        help_texts = {
            'username': 'Введите имя пользователя',
            'first_name': 'Введите имя',
            'last_name': 'Введите фамилию',
        }


class ProfileChangeForm(django.forms.ModelForm):
    """форма изменения профиля"""

    class Meta:
        model = users.models.Profile
        fields = ('image',)
        labels = {'image': 'Аватарка'}
        help_texts = {'image': 'Загрузите аватарку'}


class CreateOrganizationForm(django.forms.ModelForm):
    """создание пользователем организации"""

    class Meta:
        model = organization.models.Organization
        fields = ('name', 'description', 'is_private')

brainforces/templates/users/base.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <div class="container col-xxl-9">
    <div class="row flex-lg-row-reverse align-items-center py-5">
      <div class="col-10 col-sm-8 col-lg-6 mb-3">
        <img src="{% static 'img/login_img.jpeg' %}" class="img-fluid border rounded-3 shadow-lg " width="100%" height="auto" alt="главная картинка" />
      </div>
      <div class="col-lg-6">
        {% block user_action %}{% endblock user_action %}
      </div>
    </div>
  </div>
{% endblock content %}

brainforces/templates/users/change.html
{% extends "users/detail.html" %}

{% block user_page %}
  <form method="post" enctype="multipart/form-data">
    {% for form in forms %}
      {% include "includes/make_form.html" %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
{% endblock user_page %}

brainforces/templates/users/detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container col-xxl-9 mb-4">
    <h2 class="fw-bold display-6">
      {% if username %}
        {{ username }}
      {% else %}
        {{ user.username }}
      {% endif %}
    </h2>
    {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-tabs mb-4">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:profile' %}active{% else %}text-dark{% endif %}" {% if view_name == 'users:profile' %}aria-current="page"{% endif %} href="{% url 'users:profile' pk=request.resolver_match.kwargs.pk %}">Профиль</a>
        </li>
        {% if request.user.id == request.resolver_match.kwargs.pk %}
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:profile_change' %}active{% else %}text-dark{% endif %}" {% if view_name == 'users:profile_change' %}aria-current="page"{% endif %} href="{% url 'users:profile_change' pk=request.resolver_match.kwargs.pk %}">Изменить профиль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'users:create_organization' %}active{% else %}text-dark{% endif %}" {% if view_name == 'users:create_organization' %}aria-current="page"{% endif %} href="{% url 'users:create_organization' pk=request.resolver_match.kwargs.pk %}">Создать организацию</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:quizzes' %}active{% else %}text-dark{% endif %}" {% if view_name == 'users:quizzes' %}aria-current="page"{% endif %} href="{% url 'users:quizzes' pk=request.resolver_match.kwargs.pk %}">Соревнования</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:answers' %}active{% else %}text-dark{% endif %}" {% if view_name == 'users:answers' %}aria-current="page"{% endif %} href="{% url 'users:answers' pk=request.resolver_match.kwargs.pk %}">Посылки</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'users:organizations' %}active{% else %}text-dark{% endif %}" {% if view_name == 'users:organizations' %}aria-current="page"{% endif %} href="{% url 'users:organizations' pk=request.resolver_match.kwargs.pk %}">Организации</a>
        </li>
      </ul>
    {% endwith %}
    <div class="row flex-lg-row-reverse align-items-center">
      {% block user_page %}{% endblock user_page %}
    </div>
  </div>
{% endblock content %}

brainforces/templates/users/login.html
{% extends "users/base.html" %}

{% load static %}

{% block user_action %}
  <div class="text-center">
    <img src="{% static 'img/brain.svg' %}" class="mb-3" width="70" alt="иконка" />
    <h1 class="h3 mb-3 fw-normal">Добро пожаловать!</h1>
  </div>
  <form method="post" enctype="multipart/form-data">
    {% include "includes/make_form.html" %}
    <div class="row flex-lg-row align-items-center">
      <div class="row gap-2">
        <div class="col">
          <button type="submit" class="btn btn-primary">Войти</button>
        </div>
        <div class="col">
          <a href="{% url 'social_auth:begin' 'google-oauth2' %}">
            <img width="38px" src="{% static 'img/google.svg' %}" />
          </a>
        </div>
        <div class="col">
          <a href="{% url 'social_auth:begin' 'yandex-oauth2' %}">
            <img width="38px" src="{% static 'img/yandex.svg' %}" />
          </a>
        </div>
      </div>
    </div>
  </form>
{% endblock user_action %}

brainforces/templates/users/logout.html
{% extends "users/base.html" %}

{% block user_action %}
  <h1 class="display-5 fw-bold lh-1 mb-3">Вы вышли из аккаунта</h1>
  <div class="d-grid gap-2 d-md-flex">
    <a href="{% url 'users:login' %}"><button type="button" class="btn btn-primary btn-lg px-4 me-md-2">Войти в аккаунт</button></a>
  </div>
{% endblock user_action %}

brainforces/templates/users/organizations.html
{% extends "users/detail.html" %}

{% block user_page %}
  {% if organizations %}
    <div class="p-3">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Организация</th>
            <th scope="col">Роль</th>
            {% if user.pk == request.resolver_match.kwargs.pk %}
              <th scope="col">Действие</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for organization in organizations %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td><a class="nav-link" href="{{ organization.organization.get_absolute_url }}">{{ organization.organization.name }}</a></td>
              <td>{{ organization.get_role_display }}</td>
              {% if user.pk == request.resolver_match.kwargs.pk %}
                <td>
                  {% if organization.role == 0 %}
                    <a href="{% url 'organization:update_user_role' pk=organization.organization.pk user_pk=request.user.pk new_role=1 %}" class="nav-link">Принять</a>
                  {% else %}
                    <a href="{% url 'organization:profile' pk=organization.organization.pk %}" class="nav-link">Войти</a>
                  {% endif %}
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% include "includes/pagination.html" %}
  {% else %}
    {% include "includes/empty.html" %}
  {% endif %}
{% endblock user_page %}

brainforces/templates/users/password_change.html
{% extends "users/base.html" %}

{% load static %}

{% block user_action %}
  <div class="text-center">
    <img src="{% static 'img/brain.svg' %}" class="mb-3" width="72" height="57" alt="иконка" />
    <h1 class="h3 mb-3 fw-normal">Смена пароля</h1>
  </div>
  <form method="post" enctype="multipart/form-data">
    {% include "includes/make_form.html" %}
    <button type="submit" class="btn btn-primary">Изменить пароль</button>
  </form>
{% endblock user_action %}

brainforces/templates/users/password_change_done.html
{% extends "users/base.html" %}

{% block user_action %}
  <h1 class="display-5 fw-bold lh-1 mb-3">Вы успешно изменили пароль</h1>
{% endblock user_action %}

brainforces/templates/users/password_reset.html
{% extends "users/base.html" %}

{% load static %}

{% block user_action %}
  <div class="text-center">
    <img src="{% static 'img/brain.svg' %}" class="mb-3" width="72" height="57" alt="иконка" />
    <h1 class="h3 mb-3 fw-normal">Восстановление пароля</h1>
  </div>
  <form method="post" enctype="multipart/form-data">
    {% include "includes/make_form.html" %}
    <button type="submit" class="btn btn-primary">Восстановить</button>
  </form>
{% endblock user_action %}

brainforces/templates/users/password_reset_complete.html
{% extends "users/base.html" %}

{% block user_action %}
  <h1 class="display-5 fw-bold lh-1 mb-3">Вы успешно сменили пароль</h1>
  <div class="d-grid gap-2 d-md-flex">
    <a href="{% url 'users:login' %}"><button type="button" class="btn btn-primary btn-lg px-4 me-md-2">Войти в аккаунт</button></a>
  </div>
{% endblock user_action %}

brainforces/templates/users/password_reset_confirm.html
{% extends "users/base.html" %}

{% load static %}

{% block user_action %}
  <div class="text-center">
    <img src="{% static 'img/brain.svg' %}" class="mb-3" width="72" height="57" alt="иконка" />
    <h1 class="h3 mb-3 fw-normal">Придумайте новый пароль</h1>
  </div>
  <form method="post" enctype="multipart/form-data">
    {% include "includes/make_form.html" %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
{% endblock user_action %}

brainforces/templates/users/password_reset_done.html
{% extends "users/base.html" %}

{% block user_action %}
  <h1 class="display-5 fw-bold lh-1 mb-3">Мы отправили ссылку для восстановления пароля</h1>
{% endblock user_action %}

brainforces/templates/users/signup.html
{% extends "users/base.html" %}

{% load static %}

{% block user_action %}
  <div class="text-center">
    <img src="{% static 'img/brain.svg' %}" class="mb-3" width="72" height="57" alt="иконка" />
    <h1 class="h3 mb-3 fw-normal">Регистрация</h1>
  </div>
  <form method="post" enctype="multipart/form-data">
    {% include "includes/make_form.html" %}
    <button type="submit" class="btn btn-primary">Зерегистрироваться</button>
  </form>
{% endblock user_action %}

brainforces/templates/users/user_change.html
{% extends "users/user_detail.html" %}

{% block user_page %}
  <form method="post" enctype="multipart/form-data">
    {% for form in forms %}
      {% include "includes/make_form.html" %}
    {% endfor %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
{% endblock user_page %}