brainforces/brainforces/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.staticfiles.urls
import django.urls
import django.utils.timezone
import django.views.generic

import core.views


urlpatterns = [
    django.urls.path('', django.urls.include('homepage.urls')),
    django.urls.path('archive/', django.urls.include('archive.urls')),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path('auth/', django.urls.include('users.urls')),
    django.urls.path('auth/', django.urls.include('django.contrib.auth.urls')),
    django.urls.path('quizzes/', django.urls.include('quiz.urls')),
    django.urls.path(
        'ckeditor/', django.urls.include('ckeditor_uploader.urls')
    ),
    django.urls.path(
        'organizations/', django.urls.include('organization.urls')
    ),
    django.urls.path('about/', django.urls.include('about.urls')),
    django.urls.path(
        'social-auth/',
        django.urls.include('social_django.urls', namespace='social_auth'),
    ),
]

handler404 = core.views.custom_404
handler500 = core.views.custom_500


if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include('debug_toolbar.urls')
        ),
    )
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    else:
        urlpatterns += (
            django.contrib.staticfiles.urls.staticfiles_urlpatterns()
        )

brainforces/quiz/urls.py
import django.urls

import quiz.views


app_name = 'quiz'

urlpatterns = [
    django.urls.path('', quiz.views.QuizListView.as_view(), name='list'),
    django.urls.path(
        '<int:pk>/',
        quiz.views.QuizDetailView.as_view(),
        name='quiz_detail',
    ),
    django.urls.path(
        '<int:pk>/user_answers/',
        quiz.views.UserAnswersList.as_view(),
        name='user_answers_list',
    ),
    django.urls.path(
        '<int:pk>/questions/<int:question_pk>/',
        quiz.views.QuestionDetailView.as_view(),
        name='question_detail',
    ),
    django.urls.path(
        '<int:pk>/standings/',
        quiz.views.StandingsList.as_view(),
        name='standings_list',
    ),
    django.urls.path(
        '<int:pk>/questions/',
        quiz.views.QuestionsView.as_view(),
        name='questions',
    ),
    django.urls.path(
        '<int:pk>/register/',
        quiz.views.QuizRegistrationView.as_view(),
        name='register',
    ),
    django.urls.path(
        '<int:pk>/make_results/',
        quiz.views.MakeQuizResultsView.as_view(),
        name='make_results',
    ),
]

brainforces/quiz/forms.py
import django.contrib.admin.widgets
import django.core.exceptions
import django.forms
import django.utils.timezone

import quiz.models


class AnswerForm(django.forms.Form):
    """форма выбора варианта ответа"""

    answer = django.forms.ChoiceField(
        required=True,
        choices=[],
        widget=django.forms.RadioSelect(),
        label='Варианты ответа:',
    )


class QuizForm(django.forms.ModelForm):
    """форма создания викторины"""

    class Meta:
        model = quiz.models.Quiz
        fields = (
            'name',
            'description',
            'start_time',
            'duration',
            'is_rated',
            'is_private',
        )
        widgets = {
            'start_time': django.forms.DateTimeInput(
                attrs={
                    'class': 'form-control datetimepicker-input',
                    'data-target': '#datetimepicker1',
                }
            )
        }

    def clean_start_time(self):
        """
        валидируем время начала викторины
        она должна начинаться как минимум через 5 минут
        """
        start_time = self.cleaned_data['start_time']
        if (
            not start_time
            or not start_time - django.utils.timezone.now()
            >= django.utils.timezone.timedelta(minutes=5)
        ):
            raise django.core.exceptions.ValidationError(
                'Минимальное время начала - через 5 минут'
            )
        return start_time


class QuestionForm(django.forms.ModelForm):
    """форма создания вопроса"""

    variants = django.forms.CharField(
        label='Варианты ответа',
        help_text='Вводите варианты ответа каждый с новой строки'
        ', у правильного на конце напишите right',
        widget=django.forms.widgets.Textarea(attrs={'rows': 5}),
    )

    class Meta:
        model = quiz.models.Question
        fields = ('name', 'text', 'difficulty')

    def clean_variants(self) -> list:
        """
        валидируем варианты ответа
        их должно быть не меньше двух
        не менее одного правильного ответа
        """
        variants = list(
            map(lambda x: x.strip(), self.cleaned_data['variants'].split('\n'))
        )
        if len(variants) < 2:
            raise django.core.exceptions.ValidationError(
                'Слишком мало вариантов ответа'
            )
        if not any(map(lambda x: x.endswith('right'), variants)):
            raise django.core.exceptions.ValidationError(
                'Нет правильного варианта'
            )
        if any(map(lambda x: len(x) > 75, variants)):
            raise django.core.exceptions.ValidationError(
                'Слишком длинный вариант ответа'
            )
        return variants

brainforces/quiz/views.py
import typing

import django.contrib.auth.mixins
import django.contrib.messages
import django.db.models
import django.http
import django.shortcuts
import django.urls
import django.utils.timezone
import django.views.generic

import core.elastic_services
import core.forms
import core.views
import quiz.documents
import quiz.forms
import quiz.mixins
import quiz.models
import quiz.services


class QuizListView(core.views.ElasticSearchListView):
    """список викторин"""

    template_name = 'quiz/list.html'
    context_object_name = 'quizzes'
    paginate_by = 5
    search_fields = ['name', 'description']
    document_class = quiz.documents.QuizDocument

    def get_default_queryset(self) -> django.db.models.QuerySet:
        return quiz.models.Quiz.objects.filter_user_access(
            user_pk=self.request.user.pk
        ).order_by('-id')

    def get_context_data(self, *args, **kwargs) -> dict:
        """дополняем контекст формой поиска"""
        context = super().get_context_data(*args, **kwargs)
        form = core.forms.SearchForm()
        form.fields['search_by'].choices = (
            (1, 'Все'),
            (2, 'Имя'),
            (3, 'Описание'),
            (4, 'Организация'),
        )
        context['form'] = form
        return context


class QuizDetailView(django.views.generic.DetailView):
    """детальная информация о викторине"""

    template_name = 'quiz/quiz_detail.html'
    context_object_name = 'quiz'

    def get_queryset(self) -> django.db.models.QuerySet:
        """список викторин, проверка доступа пользователя"""
        return quiz.models.Quiz.objects.filter_user_access(
            user_pk=self.request.user.pk
        )

    def get_context_data(self, *args, **kwargs) -> dict:
        """
        право доступа к викторине для пользователя
        может ли пользователь войти в эту викторину,
        может ли он решать задания на данный момент
        """
        context = super().get_context_data(*args, **kwargs)
        quiz_obj = context['object']
        context['can_participate'] = quiz.models.QuizResults.objects.filter(
            quiz__pk=self.kwargs['pk'], user__pk=self.request.user.pk
        ).exists()
        quiz_status = quiz_obj.get_quiz_status()
        context['quiz_status'] = quiz_status
        if quiz_status == 1:
            context['can_access_questions'] = False
        elif quiz_status == 2:
            context['can_access_questions'] = context['can_participate']
        else:
            context[
                'can_access_questions'
            ] = quiz.services.user_can_access_quiz(quiz_obj, self.request.user)
        context['can_end'] = (
            quiz_status == 3 and quiz_obj.creator.pk == self.request.user.pk
        )
        context['now_time'] = str(django.utils.timezone.now())
        context['end_time'] = str(
            quiz_obj.start_time
            + django.utils.timezone.timedelta(minutes=quiz_obj.duration)
        )
        context['quiz_is_ended'] = (
            quiz_obj.start_time
            + django.utils.timezone.timedelta(minutes=quiz_obj.duration)
            < django.utils.timezone.now()
        )
        return context


class MakeQuizResultsView(django.views.generic.View):
    """администратор подводит итоги викторины"""

    def get(
        self, request: django.http.HttpRequest, pk: int
    ) -> django.http.HttpResponse:
        """
        обновляется рейтинг пользователя,
        определяется место в топе участников викторины
        проверки: существует ли квиз,
        является ли пользователь его создаталем
        """
        quiz_obj = django.shortcuts.get_object_or_404(
            quiz.models.Quiz.objects.get_only_useful_list_fields(),
            pk=pk,
            is_ended=False,
        )
        if quiz_obj.creator.pk != request.user.pk:
            raise django.http.Http404()
        quiz.services.make_quiz_results(quiz_obj)
        django.contrib.messages.success(request, 'Успешно!')
        return django.shortcuts.redirect(
            django.urls.reverse('quiz:quiz_detail', kwargs={'pk': pk}),
        )


class QuestionsView(
    quiz.mixins.AccessToQuizMixin, django.views.generic.ListView
):
    """список вопросов в викторине"""

    template_name = 'quiz/questions.html'
    context_object_name = 'questions'

    def get_queryset(self) -> django.db.models.QuerySet:
        """
        получаем все вопросы в викторине
        и количество ответов всего и только правильных
        """
        return (
            quiz.models.Question.objects.filter(quiz__pk=self.kwargs['pk'])
            .annotate(
                total_answers=django.db.models.Count(
                    'answers__id',
                    filter=django.db.models.Q(
                        answers__user__pk=self.request.user.pk
                    ),
                ),
                success_answers=django.db.models.Count(
                    'answers__id',
                    filter=django.db.models.Q(
                        answers__is_correct=True,
                        answers__user__pk=self.request.user.pk,
                    ),
                ),
            )
            .only('name')
        )


class QuestionDetailView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    quiz.mixins.AccessToQuizMixin,
    django.views.generic.DetailView,
):
    """детальная информация о вопросе"""

    template_name = 'quiz/question_detail.html'
    context_object_name = 'question'
    queryset = quiz.models.Question.objects.only('name', 'text', 'difficulty')
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, *args, **kwargs) -> typing.Dict:
        """
        рендерим вопрос, отдаем форму
        с вариантами ответа
        """
        context = super().get_context_data(*args, **kwargs)
        variants = quiz.models.Variant.objects.filter(
            question__id=self.kwargs['question_pk']
        ).only('text')
        form = quiz.forms.AnswerForm()
        form.fields['answer'].choices = [
            (variant.id, variant.text) for variant in variants
        ]
        context['form'] = form
        return context

    def post(
        self, request: django.http.HttpRequest, pk: int, question_pk: int
    ) -> django.http.HttpResponse:
        """
        сохраняем ответ пользователя
        квиз должен существовать
        вопрос должен существовать
        создаем объект ответа пользователя
        обновляем результат решенных задач
        и обновляем рейтинг, если викторина рейтинговая

        если викторина идет, пользователь не может
        дать ответ на тот же вопрос дважды
        """
        question_obj = django.shortcuts.get_object_or_404(
            quiz.models.Question.objects.select_related('quiz').only(
                'quiz__is_rated',
                'quiz__is_private',
                'id',
                'quiz__start_time',
                'quiz__duration',
            ),
            pk=question_pk,
            quiz__pk=pk,
        )
        quiz_obj = question_obj.quiz
        if quiz.services.user_can_access_quiz(quiz_obj, request.user):
            is_correct = quiz.models.Variant.objects.filter(
                pk=request.POST['answer'], is_correct=True
            ).exists()

            quiz_status = quiz_obj.get_quiz_status()
            if quiz_status == 2:
                if quiz.models.UserAnswer.objects.filter(
                    user__pk=request.user.pk, question__pk=question_pk
                ).exists():
                    django.contrib.messages.error(
                        request,
                        'Вы уже отправляли ответ на этот вопрос'
                        ' в течение викторины',
                    )
                    return django.shortcuts.redirect(
                        django.urls.reverse(
                            'quiz:question_detail',
                            kwargs={'pk': pk, 'question_pk': question_pk},
                        )
                    )

            quiz.models.UserAnswer.objects.create(
                user=request.user,
                question=question_obj,
                is_correct=is_correct,
            )
            quiz_result = quiz.models.QuizResults.objects.filter(
                quiz__pk=pk, user__pk=request.user.pk
            ).first()
            if (
                quiz_status == 2
                and quiz_result
                and is_correct
                and quiz.models.UserAnswer.objects.filter(
                    user__pk=request.user.pk,
                    question__pk=question_pk,
                    is_correct=is_correct,
                ).count()
                == 1
            ):
                quiz_result.solved += 1
                if quiz_obj.is_rated and not quiz_obj.is_private:
                    quiz_result.rating_after += question_obj.difficulty
                quiz_result.save()
        return django.shortcuts.redirect('quiz:user_answers_list', pk=pk)


class UserAnswersList(
    quiz.mixins.AccessToQuizMixin, django.views.generic.ListView
):
    """мои посылки"""

    template_name = 'quiz/user_answers_list.html'
    context_object_name = 'answers'
    paginate_by = 40

    def get_queryset(self) -> django.db.models.QuerySet:
        """получаем свои послыки в данной викторине"""
        useful_answer_fields = (
            quiz.models.UserAnswer.objects.get_only_useful_list_fields()
            .filter(
                question__quiz__id=self.kwargs['pk'],
                user__id=self.request.user.id,
            )
            .order_by('-time_answered')
        )
        return useful_answer_fields


class StandingsList(
    quiz.mixins.AccessToQuizMixin, django.views.generic.ListView
):
    """положение"""

    template_name = 'quiz/standing.html'
    context_object_name = 'results'
    paginate_by = 40

    def get_queryset(self) -> django.db.models.QuerySet:
        """
        получаем информацию о других пользователях,
        участвующих в викторине
        """

brainforces/templates/quiz/detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
  <div class="container col-xxl-9 mb-4">
    <div class="d-flex justify-content-between">
      <h2 class="fw-bold display-7">
        BrainForces Round {{ quiz.pk }}
      </h2>
      <h2 class="display-7 text-muted" id="remaining_time">
      </h2>
    </div>
    {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-tabs mb-4">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'quiz:quiz_detail' %}active{% else %}text-dark{% endif %}" {% if view_name == 'quiz:quiz_detail' %}aria-current="page"{% endif %} href="{% url 'quiz:quiz_detail' pk=quiz.pk %}">Описание</a>
        </li>
        {% if can_access_questions %}
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'quiz:questions' or view_name == 'quiz:question_detail' %}active{% else %}text-dark{% endif %}" {% if view_name == 'quiz:questions' or view_name == 'quiz:question_detail' %}aria-current="page"{% endif %} href="{% url 'quiz:questions' pk=quiz.pk %}">Вопросы</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'quiz:user_answers_list' %}active{% else %}text-dark{% endif %}" {% if view_name == 'quiz:user_answers_list' %}aria-current="page"{% endif %} href="{% url 'quiz:user_answers_list' pk=quiz.pk %}">Мои попытки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'quiz:standings_list' %}active{% else %}text-dark{% endif %}" {% if view_name == 'quiz:standings_list' %}aria-current="page"{% endif %} href="{% url 'quiz:standings_list' pk=quiz.pk %}">Положение</a>
          </li>
        {% endif %}
      </ul>
    {% endwith %}
    <div class="row flex-lg-row-reverse align-items-center">
      {% block quiz_page %}{% endblock quiz_page %}
    </div>
  </div>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      function timer() {
        remaining_time -= 1000;

        if (remaining_time <= 0) {
            clearInterval(countdown_timer);
            location.reload();
        }

        var hours = Math.floor(remaining_time / (1000 * 60 * 60)).toString();
        var minutes = Math.floor((remaining_time % (1000 * 60 * 60)) / (1000 * 60)).toString();
        var seconds = Math.floor((remaining_time % (1000 * 60)) / 1000).toString();
        if (hours.length == 1){
          var hours = '0' + hours;
        }
        if (minutes.length == 1){
          var minutes = '0' + minutes;
        }
        if (seconds.length == 1){
          var seconds = '0' + seconds;
        }

        var countdown_element = document.getElementById('remaining_time');
        if (seconds >= 0){
          countdown_element.innerHTML = hours + ':' + minutes + ':' + seconds;
        }
      }
      var now_time = new Date('{{ now_time }}');
      var end_time = new Date('{{ end_time }}');
  
      var remaining_time = Math.max(0, end_time - now_time);
      if (remaining_time >= 1 && '{{ quiz_status }}' == '2'){
        timer();
        var countdown_timer = setInterval(timer, 1000);
      }
      else{
        var countdown_element = document.getElementById('remaining_time');
        countdown_element.innerHTML = '{{ quiz.get_status_display }}';
      }
  });
  </script>
{% endblock content %}

brainforces/templates/quiz/list.html
{% extends "base.html" %}

{% block content %}
  <div class="container col-xxl-9">
    {% include "includes/search_form.html" %}
    {% if quizzes %}
      {% for quiz in quizzes %}
        <div class="col-12">
          <div class="card shadow-sm mb-2">
            <div class="card-body">
              {% include "includes/quiz_detail.html" %}
            </div>
          </div>
        </div>
      {% endfor %}
      {% include "includes/pagination.html" %}
    {% else %}
      {% include "includes/empty.html" %}
    {% endif %}
  </div>
{% endblock content %}

brainforces/templates/quiz/question_detail.html
{% extends "quiz/detail.html" %}

{% load widget_tweaks %}

{% block quiz_page %}
  <div class="text-center">
    <h3>{{ question.name }}</h3>
    <h5> сложность: {{ question.difficulty }}</h5>
  </div>
  <p>{{ question.text|safe }}</p>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <div class="row gy-3">
        <div class="col-12">
          <form>
            {% csrf_token %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger" role="alert">
                {{ error|safe }}
              </div>
            {% endfor %}
            {% for field in form.visible_fields %}
              <p>
                {{ field.label }}
                <div class="row">
                  {% for ques_id, variant_txt in form.fields.answer.choices %}
                    <div class="col-sm-12 col-md-6">
                      <div class="card">
                        <div class="card-body">
                          <input type="radio" name="answer" value="{{ ques_id }}" class="form-check-input" required="" id="id_answer_{{ forloop.counter0 }}" />
                          <label class="form-check-label">
                            {{ variant_txt }}
                          </label>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
                <small><span class="text-muted">{{ field.help_text }}</span></small>
                {% for error in field.errors %}
                  <div class="alert alert-danger" role="alert">
                    {{ error|safe }}
                  </div>
                {% endfor %}
              </p>
            {% endfor %}
            <button type="sumbit" class="btn btn-primary">Ответить</button>
          </form>
        </div>
      </div>
    </div>
  </form>
{% endblock quiz_page %}

brainforces/templates/quiz/questions.html
{% extends "quiz/detail.html" %}

{% block quiz_page %}
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">№</th>
        <th scope="col">Название</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for question in questions %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td> <a href="{% url 'quiz:question_detail' pk=quiz.pk question_pk=question.pk %}"> {{ question.name }} </a></td>
          <td class="{% if question.total_answers > 0 and question.success_answers > 0 %}table-success{% elif question.total_answers > 0 %}table-danger{% endif %}"></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock quiz_page %}

brainforces/templates/quiz/quiz_detail.html
{% extends "quiz/detail.html" %}

{% block quiz_page %}
  <h3 class="display-8 fw-bold lh-1 mb-3">{{ quiz.name }}</h3>
  <div>
    <span class="badge badge-pill text-bg-primary">{{ quiz.get_status_display }}</span>
    {% if quiz.is_ended %}
      <span class="badge badge-pill text-bg-primary">Итоги подведены</span>
    {% endif %}
  </div>
  <p class="lead">{{ quiz.description|safe }}</p>
  <p class="lead">Начало: {{ quiz.start_time }}</p>
  <p class="lead">Продолжительность: {{ quiz.duration }} минут</p>
  <p class="lead">Создатель викторины: <span class="badge badge-pill text-bg-secondary">{{ quiz.creator.username }}</span></p>
  {% if quiz.organized_by.name %}
    <p class="lead">Организация: <span class="badge badge-pill text-bg-secondary">{{ quiz.organized_by.name }}</span></p>
  {% endif %}
  {% if quiz_status == 1 and not can_participate or quiz_status == 2 and not can_participate %}
    <div><a href="{% url 'quiz:register' pk=quiz.pk %}" class="btn btn-primary">Зарегистрироваться</a></div>
  {% endif %}
  {% if quiz_status == 3 and quiz.creator.pk == request.user.pk and not quiz.is_ended %}
    <div><a href="{% url 'quiz:make_results' pk=quiz.pk %}" class="btn btn-primary">Подвести итоги</a></div>
  {% endif %}
{% endblock quiz_page %}

brainforces/templates/quiz/standing.html
{% extends "quiz/detail.html" %}

{% block quiz_page %}
  <div class="p-3">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">№</th>
          <th scope="col">Кто</th>
          <th scope="col">Решено</th>
        </tr>
      </thead>
      <tbody>
        {% for result in results %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td><a class="nav-link" href="{{ result.user.get_absolute_url }}">{{ result.user.username }}</a></td>
            <td>{{ result.solved }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock quiz_page %}

brainforces/templates/quiz/user_answers_list.html
{% extends "quiz/detail.html" %}

{% block quiz_page %}
  <div class="p-3">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">№</th>
          <th scope="col">Когда</th>
          <th scope="col">Кто</th>
          <th scope="col">Вопрос</th>
          <th scope="col">Вердикт</th>
        </tr>
      </thead>
      <tbody>
        {% for answer in answers %}
          <tr>
            <td>{{ forloop.revcounter }}</td>
            <td>{{ answer.time_answered|date:'Y.m.d H:m:s' }}</td>
            <td>{{ answer.user.username }}</td>
            <td>{{ answer.question.id }} - {{ answer.question.name }}</td>
            <td>
              <span class="text-{% if answer.is_correct %}success{% else %}danger{% endif %}">
              {% if answer.is_correct %}Верно{% else %}Неверно{% endif %}
              </span>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock quiz_page %}