brainforces/about/urls.py
import django.urls
import django.views.generic


app_name = 'about'

urlpatterns = [
    django.urls.path(
        '',
        django.views.generic.TemplateView.as_view(
            template_name='about/about.html'
        ),
        name='about',
    )
]

brainforces/archive/urls.py
import django.urls

import archive.views


app_name = 'archive'

urlpatterns = [
    django.urls.path(
        '', archive.views.ArchiveQuestionsView.as_view(), name='archive'
    ),
]

brainforces/brainforces/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.staticfiles.urls
import django.urls
import django.utils.timezone
import django.views.generic

import core.views


urlpatterns = [
    django.urls.path('', django.urls.include('homepage.urls')),
    django.urls.path('archive/', django.urls.include('archive.urls')),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path('auth/', django.urls.include('users.urls')),
    django.urls.path('auth/', django.urls.include('django.contrib.auth.urls')),
    django.urls.path('quizzes/', django.urls.include('quiz.urls')),
    django.urls.path(
        'ckeditor/', django.urls.include('ckeditor_uploader.urls')
    ),
    django.urls.path(
        'organizations/', django.urls.include('organization.urls')
    ),
    django.urls.path('about/', django.urls.include('about.urls')),
    django.urls.path(
        'social-auth/',
        django.urls.include('social_django.urls', namespace='social_auth'),
    ),
]

handler404 = core.views.custom_404
handler500 = core.views.custom_500


if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include('debug_toolbar.urls')
        ),
    )
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    else:
        urlpatterns += (
            django.contrib.staticfiles.urls.staticfiles_urlpatterns()
        )

brainforces/homepage/urls.py
import django.urls

import homepage.views


app_name = 'homepage'

urlpatterns = [
    django.urls.path('', homepage.views.HomeView.as_view(), name='homepage'),
]

brainforces/quiz/urls.py
import django.urls

import quiz.views


app_name = 'quiz'

urlpatterns = [
    django.urls.path('', quiz.views.QuizListView.as_view(), name='list'),
    django.urls.path(
        '<int:pk>/',
        quiz.views.QuizDetailView.as_view(),
        name='quiz_detail',
    ),
    django.urls.path(
        '<int:pk>/user_answers/',
        quiz.views.UserAnswersList.as_view(),
        name='user_answers_list',
    ),
    django.urls.path(
        '<int:pk>/questions/<int:question_pk>/',
        quiz.views.QuestionDetailView.as_view(),
        name='question_detail',
    ),
    django.urls.path(
        '<int:pk>/standings/',
        quiz.views.StandingsList.as_view(),
        name='standings_list',
    ),
    django.urls.path(
        '<int:pk>/questions/',
        quiz.views.QuestionsView.as_view(),
        name='questions',
    ),
    django.urls.path(
        '<int:pk>/register/',
        quiz.views.QuizRegistrationView.as_view(),
        name='register',
    ),
    django.urls.path(
        '<int:pk>/make_results/',
        quiz.views.MakeQuizResultsView.as_view(),
        name='make_results',
    ),
]

brainforces/users/urls.py
import django.contrib.auth.views
import django.urls

import users.forms
import users.views


app_name = 'users'

urlpatterns = [
    django.urls.path(
        'login/',
        django.contrib.auth.views.LoginView.as_view(
            template_name='users/login.html',
            form_class=users.forms.CustomAuthenticationForm,
        ),
        name='login',
    ),
    django.urls.path(
        'logout/',
        django.contrib.auth.views.LogoutView.as_view(
            template_name='users/logout.html'
        ),
        name='logout',
    ),
    django.urls.path(
        'password_change/',
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            form_class=users.forms.CustomPasswordChangeForm,
        ),
        name='password_change',
    ),
    django.urls.path(
        'password_change/done/',
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    django.urls.path(
        'password_reset/',
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            form_class=users.forms.CustomPasswordResetForm,
        ),
        name='password_reset',
    ),
    django.urls.path(
        'password_reset/done/',
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    django.urls.path(
        'reset/<uidb64>/<token>/',
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            form_class=users.forms.CustomSetPasswordForm,
        ),
        name='password_reset_confirm',
    ),
    django.urls.path(
        'reset/done/',
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    django.urls.path(
        'signup/', users.views.SignupView.as_view(), name='signup'
    ),
    django.urls.path(
        'activate/<uidb64>/<token>/',
        users.views.ActivateUserView.as_view(),
        name='activate_user',
    ),
    django.urls.path(
        '<int:pk>/',
        users.views.UserProfileView.as_view(),
        name='profile',
    ),
    django.urls.path(
        '<int:pk>/change/',
        users.views.UserProfileChangeView.as_view(),
        name='profile_change',
    ),
    django.urls.path(
        'users/',
        users.views.UserListView.as_view(),
        name='list',
    ),
    django.urls.path(
        'reset_login_attempts/<uidb64>/<token>/',
        users.views.ResetLoginAttemptsView.as_view(),
        name='reset_login_attempts',
    ),
    django.urls.path(
        '<int:pk>/answers/',
        users.views.UserAnswersView.as_view(),
        name='answers',
    ),
    django.urls.path(
        '<int:pk>/quizzes/',
        users.views.UserQuizzesView.as_view(),
        name='quizzes',
    ),
    django.urls.path(
        '<int:pk>/organizations/',
        users.views.UserOrganizationsView.as_view(),
        name='organizations',
    ),
    django.urls.path(
        '<int:pk>/create_organization/',
        users.views.CreateOrganizationView.as_view(),
        name='create_organization',
    ),
]

brainforces/templates/includes/empty.html
{% load static %}

<div class="row flex-lg-row-reverse align-items-center pl-2 mb-4">
  <div class="col-10 col-sm-8 col-lg-6 mb-3">
    <img src="{% static 'img/login_img.jpeg' %}" class="img-fluid border rounded-3 shadow-lg" width="100%" height="auto" alt="главная картинка" />
  </div>
  <div class="col-lg-6">
    <h3 class="display-5 lh-2">Пока что тут пусто</h3>
  </div>
</div>

brainforces/templates/includes/footer.html
{% load static %}

<footer class="my-4 mt-auto">
  <div class="container col-xxl-9 pt-3 border-top d-flex flex-wrap justify-content-between align-items-center">
    <div class="col-md-4 d-flex align-items-center">
      <a href="{% url 'homepage:homepage' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <img src="{% static 'img/brain.svg' %}" width="45" alt="иконка" />
      </a>
    </div>
    <span class="text-muted"> ©️BrainForces, {% now "Y" %} </span>
    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3">
        <a href="https://t.me/bebra_dev" target=blank>
          <img src="{% static 'img/telegram.svg' %}" width="24" height="24" alt="телега" />
        </a>
      </li>
      <li class="ms-3">
        <a href="https://github.com/fivan999" target=blank>
          <img src="{% static 'img/github.svg' %}" width="24" height="24" alt="гит" />
        </a>
      </li>
    </ul>
  </div>
</footer>

brainforces/templates/includes/header.html
{% load static %}

<header class="text-dark pt-3">
  <div class="container col-xxl-9">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between mb-2">
      <a href="/" class="d-flex align-items-left mb-2 mb-lg-0 text-white text-decoration-none">
        <img src="{% static 'img/brainforces.svg' %}" width="300" alt="иконка" />
      </a>
      <div class="dropdown text-end">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
          <img alt="аватарка" src="{% if request.user.profile.image %}{{ request.user.profile.get_image_50x50.url }}{% else %}{% static 'img/default_user.svg' %}{% endif %}" width="50" height="50" class="rounded-circle" />
        </a>
        <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser">
          {% if request.user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'users:profile' pk=request.user.id %}">{{ request.user.username }}</a>
            {% if request.user.is_staff %}
              <a href="/admin/" class="dropdown-item">В админку</a>
            {% endif %}
            <li><hr class="dropdown-divider" /></li>
            <a class="dropdown-item" href="{% url 'users:password_change' %}">Сменить пароль</a>
            <a class="dropdown-item" href="{% url 'users:password_reset' %}">Восстановить пароль</a>
            <li><hr class="dropdown-divider" /></li>
            <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
          {% else %}
            <a class="dropdown-item" href="{% url 'users:login' %}">Войти</a>
            <a class="dropdown-item" href="{% url 'users:signup' %}">Зарегистрироваться</a>
            <li><hr class="dropdown-divider" /></li>
            <a class="dropdown-item" href="{% url 'users:password_reset' %}">Восстановить пароль</a>
          {% endif %}
        </ul>
      </div>
    </div>
    <div>
      {% with request.resolver_match.app_name as app_name %}
        <ul class="nav nav-pills d-flex flex-wrap align-items-center justify-content-center justify-content-md-between mb-2 border rounded-4 p-2">
          <li class="nav-item">
            <a href="{% url 'homepage:homepage' %}" class="nav-link{% if app_name == 'homepage' %} active text-white{% else %} text-dark{% endif %}">Главная</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'quiz:list' %}" class="nav-link{% if app_name == 'quiz' %} active text-white{% else %} text-dark{% endif %}">Викторины</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'archive:archive' %}" class="nav-link{% if app_name == 'archive' %} active text-white{% else %} text-dark{% endif %}">Архив</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'users:list' %}" class="nav-link{% if request.resolver_match.view_name == 'users:list' %} active text-white{% else %} text-dark{% endif %}">Рейтинг</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'organization:list' %}" class="nav-link{% if app_name == 'organization' %} active text-white{% else %} text-dark{% endif %}">Организации</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'about:about' %}" class="nav-link{% if app_name == 'about' %} active text-white{% else %} text-dark{% endif %}">О сайте</a>
          </li>
        </ul>
      {% endwith %}
    </div>
  </div>
</header>

brainforces/templates/includes/like_block.html
{% load static %}

{% if request.user.is_authenticated %}
  <div class="d-flex gap-2">
    <img id="like" width="25" {% if post.is_liked_by_user %}src="{% static 'img/liked.svg' %}"{% else %}src="{% static 'img/unliked.svg' %}"{% endif %} data-link="{% url 'organization:like_post' pk=post.posted_by.pk post_pk=post.pk %}" data-orgid="{{ post.posted_by.pk }}" data-postid="{{ post.pk }}" data-action="{% if post.is_liked_by_user %}un{% endif %}like">
    <span id="total-likes-{{ post.pk }}">{{ post.likes_num }}</span>
  </div>
{% endif %}

brainforces/templates/includes/make_form.html
{% load widget_tweaks %}

{% csrf_token %}
{% for error in form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {{ error|safe }}
  </div>
{% endfor %}
{% for field in form.visible_fields %}
  <p>
    {{ field.label }}
    {{ field|add_class:"form-control" }}
    <small><span class="text-muted">{{ field.help_text }}</span></small>
    {% for error in field.errors %}
      <div class="alert alert-danger" role="alert">
        {{ error|safe }}
      </div>
    {% endfor %}
  </p>
{% endfor %}

brainforces/templates/includes/pagination.html
<ul class="pagination mt-2">
  {% if page_obj.has_previous %}
    {% if page_obj.number|add:'-3' > 1 %}
      <li class="page-item">
        <a class="page-link" href="?page=1">1</a>
      </li>
    {% endif %}
    {% if page_obj.number|add:'-3' >= 3 %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number|add:'-3' }}">
          ...
        </a>
      </li>
    {% endif %}
  {% endif %}
  {% if paginator.page_range|length > 1 %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="">{{ i }}</a>
        </li>
      {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
  {% endif %}
  {% if page_obj.has_next %}
    {% if page_obj.number|add:'4' < page_obj.paginator.num_pages %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number|add:'3' }}">...</a>
      </li>
    {% endif %}
    {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          {{ page_obj.paginator.num_pages }}
        </a>
      </li>
    {% endif %}
  {% endif %}
</ul>

brainforces/templates/includes/quiz_detail.html
<h3 class="display-7 fw-bold lh-1 mb-3">BrainForces Round {{ quiz.pk }}</h3>
<h3 class="display-8 fw-bold lh-1 mb-3">{{ quiz.name }}</h3>
<div>
  <span class="badge badge-pill text-bg-primary">{{ quiz.get_status_display }}</span>
  {% if quiz.is_ended %}
    <span class="badge badge-pill text-bg-primary">Итоги подведены</span>
  {% endif %}
</div>
<p class="lead">{{ quiz.description|safe }}</p>
<p class="lead">Начало: {{ quiz.start_time }}</p>
<p class="lead">Продолжительность: {{ quiz.duration }} минут</p>
<p class="lead">Создатель викторины: <span class="badge badge-pill text-bg-secondary">{{ quiz.creator.username }}</span></p>
{% if quiz.organized_by.name %}
  <p class="lead">Организация: <span class="badge badge-pill text-bg-secondary">{{ quiz.organized_by.name }}</span></p>
{% endif %}
<a href="{{ quiz.get_absolute_url }}" class="btn btn-primary">Смотреть</a>

brainforces/templates/includes/search_form.html
{% load widget_tweaks %}

<form method="get" class="mb-2">
  {% csrf_token %}
  <div class="d-flex justify-content-between">
    <div class="col-8">
      <input type="text" name="query" placeholder="Поиск" class="form-control" id="id_query">
    </div>
    <button class="btn btn-primary col-4" type="submit">Найти</button>
  </div>
</form>

brainforces/templates/includes/total_views_block.html
{% load static %}

<div class="d-flex gap-2">
  <div><img src="{% static 'img/eye.svg' %}" width="29" /></div>
  <div>{{ total_views }}</div>
</div>