brainforces/brainforces/urls.py
import django.conf
import django.conf.urls.static
import django.contrib.admin
import django.contrib.staticfiles.urls
import django.urls
import django.utils.timezone
import django.views.generic

import core.views


urlpatterns = [
    django.urls.path('', django.urls.include('homepage.urls')),
    django.urls.path('archive/', django.urls.include('archive.urls')),
    django.urls.path('admin/', django.contrib.admin.site.urls),
    django.urls.path('auth/', django.urls.include('users.urls')),
    django.urls.path('auth/', django.urls.include('django.contrib.auth.urls')),
    django.urls.path('quizzes/', django.urls.include('quiz.urls')),
    django.urls.path(
        'ckeditor/', django.urls.include('ckeditor_uploader.urls')
    ),
    django.urls.path(
        'organizations/', django.urls.include('organization.urls')
    ),
    django.urls.path('about/', django.urls.include('about.urls')),
    django.urls.path(
        'social-auth/',
        django.urls.include('social_django.urls', namespace='social_auth'),
    ),
]

handler404 = core.views.custom_404
handler500 = core.views.custom_500


if django.conf.settings.DEBUG:
    urlpatterns += (
        django.urls.path(
            '__debug__/', django.urls.include('debug_toolbar.urls')
        ),
    )
    if django.conf.settings.MEDIA_ROOT:
        urlpatterns += django.conf.urls.static.static(
            django.conf.settings.MEDIA_URL,
            document_root=django.conf.settings.MEDIA_ROOT,
        )
    else:
        urlpatterns += (
            django.contrib.staticfiles.urls.staticfiles_urlpatterns()
        )

brainforces/organization/urls.py
import django.urls

import organization.views


app_name = 'organization'

urlpatterns = [
    django.urls.path(
        '<int:pk>/',
        organization.views.OrganizationMainView.as_view(),
        name='profile',
    ),
    django.urls.path(
        '<int:pk>/users/',
        organization.views.OrganizationUsersView.as_view(),
        name='users',
    ),
    django.urls.path(
        '<int:pk>/join/',
        organization.views.JoinOrganizationView.as_view(),
        name='join',
    ),
    django.urls.path(
        '<int:pk>/quizzes/',
        organization.views.OrganizationQuizzesView.as_view(),
        name='quizzes',
    ),
    django.urls.path(
        '<int:pk>/users/<int:user_pk>/delete/',
        organization.views.DeleteUserFromOrganizationView.as_view(),
        name='delete_user',
    ),
    django.urls.path(
        '<int:pk>/users/<int:user_pk>/update/<int:new_role>/',
        organization.views.UpdateUserOrganizationRoleView.as_view(),
        name='update_user_role',
    ),
    django.urls.path(
        '',
        organization.views.OrganizationListView.as_view(),
        name='list',
    ),
    django.urls.path(
        '<int:pk>/posts/',
        organization.views.OrganizationPostsView.as_view(),
        name='posts',
    ),
    django.urls.path(
        '<int:pk>/posts/<int:post_pk>/',
        organization.views.PostCommentsView.as_view(),
        name='post_detail',
    ),
    django.urls.path(
        '<int:pk>/posts/<int:post_pk>/like/',
        organization.views.CreateLikeView.as_view(),
        name='like_post',
    ),
    django.urls.path(
        '<int:pk>/create_quiz/',
        organization.views.QuizCreateView.as_view(),
        name='create_quiz',
    ),
    django.urls.path(
        '<int:pk>/create_post/',
        organization.views.CreatePostView.as_view(),
        name='create_post',
    ),
]

brainforces/quiz/urls.py
import django.urls

import quiz.views


app_name = 'quiz'

urlpatterns = [
    django.urls.path('', quiz.views.QuizListView.as_view(), name='list'),
    django.urls.path(
        '<int:pk>/',
        quiz.views.QuizDetailView.as_view(),
        name='quiz_detail',
    ),
    django.urls.path(
        '<int:pk>/user_answers/',
        quiz.views.UserAnswersList.as_view(),
        name='user_answers_list',
    ),
    django.urls.path(
        '<int:pk>/questions/<int:question_pk>/',
        quiz.views.QuestionDetailView.as_view(),
        name='question_detail',
    ),
    django.urls.path(
        '<int:pk>/standings/',
        quiz.views.StandingsList.as_view(),
        name='standings_list',
    ),
    django.urls.path(
        '<int:pk>/questions/',
        quiz.views.QuestionsView.as_view(),
        name='questions',
    ),
    django.urls.path(
        '<int:pk>/register/',
        quiz.views.QuizRegistrationView.as_view(),
        name='register',
    ),
    django.urls.path(
        '<int:pk>/make_results/',
        quiz.views.MakeQuizResultsView.as_view(),
        name='make_results',
    ),
]

brainforces/users/urls.py
import django.contrib.auth.views
import django.urls

import users.forms
import users.views


app_name = 'users'

urlpatterns = [
    django.urls.path(
        'login/',
        django.contrib.auth.views.LoginView.as_view(
            template_name='users/login.html',
            form_class=users.forms.CustomAuthenticationForm,
        ),
        name='login',
    ),
    django.urls.path(
        'logout/',
        django.contrib.auth.views.LogoutView.as_view(
            template_name='users/logout.html'
        ),
        name='logout',
    ),
    django.urls.path(
        'password_change/',
        django.contrib.auth.views.PasswordChangeView.as_view(
            template_name='users/password_change.html',
            form_class=users.forms.CustomPasswordChangeForm,
        ),
        name='password_change',
    ),
    django.urls.path(
        'password_change/done/',
        django.contrib.auth.views.PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done',
    ),
    django.urls.path(
        'password_reset/',
        django.contrib.auth.views.PasswordResetView.as_view(
            template_name='users/password_reset.html',
            form_class=users.forms.CustomPasswordResetForm,
        ),
        name='password_reset',
    ),
    django.urls.path(
        'password_reset/done/',
        django.contrib.auth.views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done',
    ),
    django.urls.path(
        'reset/<uidb64>/<token>/',
        django.contrib.auth.views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            form_class=users.forms.CustomSetPasswordForm,
        ),
        name='password_reset_confirm',
    ),
    django.urls.path(
        'reset/done/',
        django.contrib.auth.views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete',
    ),
    django.urls.path(
        'signup/', users.views.SignupView.as_view(), name='signup'
    ),
    django.urls.path(
        'activate/<uidb64>/<token>/',
        users.views.ActivateUserView.as_view(),
        name='activate_user',
    ),
    django.urls.path(
        '<int:pk>/',
        users.views.UserProfileView.as_view(),
        name='profile',
    ),
    django.urls.path(
        '<int:pk>/change/',
        users.views.UserProfileChangeView.as_view(),
        name='profile_change',
    ),
    django.urls.path(
        'users/',
        users.views.UserListView.as_view(),
        name='list',
    ),
    django.urls.path(
        'reset_login_attempts/<uidb64>/<token>/',
        users.views.ResetLoginAttemptsView.as_view(),
        name='reset_login_attempts',
    ),
    django.urls.path(
        '<int:pk>/answers/',
        users.views.UserAnswersView.as_view(),
        name='answers',
    ),
    django.urls.path(
        '<int:pk>/quizzes/',
        users.views.UserQuizzesView.as_view(),
        name='quizzes',
    ),
    django.urls.path(
        '<int:pk>/organizations/',
        users.views.UserOrganizationsView.as_view(),
        name='organizations',
    ),
    django.urls.path(
        '<int:pk>/create_organization/',
        users.views.CreateOrganizationView.as_view(),
        name='create_organization',
    ),
]

brainforces/users/models.py
import transliterate

import django.contrib.auth.models
import django.db.models
import django.urls

import core.models
import users.managers


def generate_image_path(obj: django.db.models.Model, filename: str) -> str:
    """генерируем файловый пусть к картинке"""
    filename = transliterate.translit(filename, 'ru', reversed=True)
    return f'users/{obj.user.pk}/{filename}'


class User(django.contrib.auth.models.AbstractUser):
    """кастомный пользователь"""

    objects = users.managers.UserManager()
    email = django.db.models.EmailField(
        verbose_name='почта',
        help_text='Электронная почта пользователя',
        blank=True,
        max_length=100,
        unique=True,
    )
    login_attempts = django.db.models.IntegerField(
        default=0,
        verbose_name='неудачные попытки',
        help_text='Количество неудачных попыток входа в аккаунт',
    )

    class Meta(django.contrib.auth.models.AbstractUser.Meta):
        db_table = 'auth_user'
        swappable = 'AUTH_USER_MODEL'

    def get_absolute_url(self) -> str:
        """путь к user_detail"""
        return django.urls.reverse_lazy(
            'users:profile', kwargs={'pk': self.pk}
        )


class Profile(core.models.AbstractImageModel):
    """профиль пользователя"""

    user = django.db.models.OneToOneField(
        User,
        related_name='profile',
        verbose_name='профиль',
        help_text='Профиль пользователя',
        on_delete=django.db.models.CASCADE,
        blank=True,
        null=True,
    )
    image = django.db.models.ImageField(
        blank=True,
        verbose_name='аватарка',
        help_text='Аватарка пользователя',
        upload_to=generate_image_path,
        null=True,
    )
    rating = django.db.models.PositiveIntegerField(
        verbose_name='рейтинг', help_text='Рейтинг пользователя', default=0
    )

    class Meta:
        verbose_name = 'профиль'
        verbose_name_plural = 'профили'

    def __str__(self) -> str:
        """строковое представление"""
        return f'Профиль пользователя {self.user.pk}'

brainforces/organization/forms.py
import django.core.exceptions
import django.db.models
import django.forms

import organization.models
import users.models


class InviteToOrganizationForm(django.forms.Form):
    """форма приглашения нового пользователя"""

    username = django.forms.CharField(help_text='Имя или почта')

    def clean_username(self) -> str:
        """
        валидируем пользователя: имя или почта
        должны существовать
        """
        username = self.cleaned_data['username']
        user = users.models.User.objects.get_user_by_username_or_email(
            username=username
        )
        if user is None:
            raise django.core.exceptions.ValidationError('Ошибка')
        self.cleaned_data['user_obj'] = user
        return username


class PostForm(django.forms.ModelForm):
    """форма создания поста организации"""

    class Meta:
        model = organization.models.OrganizationPost
        fields = ('name', 'text', 'is_private')

brainforces/users/forms.py
import django.contrib.auth.forms
import django.contrib.auth.tokens
import django.core.exceptions
import django.forms

import organization.models
import users.models
import users.tasks


class SignUpForm(django.contrib.auth.forms.UserCreationForm):
    """форма регистрации"""

    class Meta(django.contrib.auth.forms.UserCreationForm.Meta):
        fields = ('username', 'email', 'password1', 'password2')
        model = users.models.User

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Имя пользователя'
        self.fields['username'].help_text = 'Не более 150 символов. '
        'Только буквы, цифры и символы @/./+/-/_.'

        self.fields['email'].label = 'Почта'
        self.fields['email'].help_text = 'Введите адрес электронной почты'

        self.fields['password1'].label = 'Пароль'
        self.fields['password1'].help_text = 'Придумайте пароль'

        self.fields['password2'].label = 'Пароль еще раз'
        self.fields['password2'].help_text = 'Подтвердите пароль'


class CustomAuthenticationForm(django.contrib.auth.forms.AuthenticationForm):
    """форма авторизации"""

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Имя пользователя'
        self.fields['username'].help_text = 'Введите имя польвователя'

        self.fields['password'].label = 'Пароль'
        self.fields['password'].help_text = 'Введите пароль'


class CustomPasswordChangeForm(django.contrib.auth.forms.PasswordChangeForm):
    """форма смены пароля"""

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['old_password'].label = 'Старый пароль'
        self.fields['old_password'].help_text = 'Введите старый пароль'

        self.fields['new_password1'].label = 'Новый пароль'
        self.fields['new_password1'].help_text = 'Придумайте пароль'

        self.fields['new_password2'].label = 'Пароль еще раз'
        self.fields['new_password2'].help_text = 'Подтвердите пароль'


class CustomPasswordResetForm(django.contrib.auth.forms.PasswordResetForm):
    """форма для отправки письма для восстановления пароля"""

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'Почта'
        self.fields[
            'email'
        ].help_text = 'Введите электронную почту, к которой привязан аккаунт'

    def clean_email(self) -> str:
        """нормализуем почту"""
        email = users.models.User.objects.normalize_email(
            self.cleaned_data['email']
        )
        user_obj = (
            users.models.User.objects.filter(email=email, is_active=True)
            .only('email')
            .first()
        )
        if user_obj:
            return email
        raise django.core.exceptions.ValidationError(
            'Нет пользователя с такой почтой'
        )

    def send_mail(self, *args, **kwargs) -> None:
        """отправка почты для смены пароля"""
        context = args[2]
        token_generator = django.contrib.auth.tokens.default_token_generator
        users.tasks.send_email_with_token.delay(
            user_id=context['user'].pk,
            template_name='users/emails/reset_password.html',
            subject='Восстановление пароля',
            where_to='users:password_reset_confirm',
            domain=context['domain'],
            protocol=context['protocol'],
            token=token_generator.make_token(context['user']),
        )


class CustomSetPasswordForm(django.contrib.auth.forms.SetPasswordForm):
    """форма для нового пароля"""

    def __init__(self, *args, **kwargs) -> None:
        """переопределяем поля"""
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].label = 'Новый пароль'
        self.fields['new_password1'].help_text = 'Придумайте пароль'

        self.fields['new_password2'].label = 'Пароль еще раз'
        self.fields['new_password2'].help_text = 'Подтвердите пароль'


class CustomUserChangeForm(django.contrib.auth.forms.UserChangeForm):
    """форма изменения пользователя"""

    password = None

    class Meta:
        model = users.models.User
        fields = ('username', 'first_name', 'last_name')
        labels = {
            'username': 'Имя пользователя',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        help_texts = {
            'username': 'Введите имя пользователя',
            'first_name': 'Введите имя',
            'last_name': 'Введите фамилию',
        }


class ProfileChangeForm(django.forms.ModelForm):
    """форма изменения профиля"""

    class Meta:
        model = users.models.Profile
        fields = ('image',)
        labels = {'image': 'Аватарка'}
        help_texts = {'image': 'Загрузите аватарку'}


class CreateOrganizationForm(django.forms.ModelForm):
    """создание пользователем организации"""

    class Meta:
        model = organization.models.Organization
        fields = ('name', 'description', 'is_private')

brainforces/templates/organization/create_post.html
{% extends "organization/detail.html" %}

{% load widget_tweaks %}

{% block organization_page %}
  <form method="post" class="mb-2">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger" role="alert">
        {{ error|safe }}
      </div>
    {% endfor %}
    {% for field in form.visible_fields %}
      <p>
        {{ field.label }}
        {% if field.name == 'is_private' %}
          {{ field|add_class:"form-check-input" }}
        {% else %}
          {{ field|add_class:"form-control" }}
        {% endif %}
        <small><span class="text-muted">{{ field.help_text }}</span></small>
        {% for error in field.errors %}
          <div class="alert alert-danger" role="alert">
            {{ error|safe }}
          </div>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Создать</button>
  </form>
{% endblock organization_page %}

brainforces/templates/organization/detail.html
{% extends "base.html" %}

{% block content %}
  <div class="container col-xxl-9">
    <h2 class="fw-bold display-7">
      {{ organization.name }}
    </h2>
    {% with request.resolver_match.view_name as view_name %}
      <ul class="nav nav-tabs mb-4">
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'organization:profile' %}active{% else %}text-dark{% endif %}" {% if view_name == 'organization:profile' %}aria-current="page"{% endif %} href="{% url 'organization:profile' pk=request.resolver_match.kwargs.pk %}">Профиль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'organization:users' %}active{% else %}text-dark{% endif %}" {% if view_name == 'organization:users' %}aria-current="page"{% endif %} href="{% url 'organization:users' pk=request.resolver_match.kwargs.pk %}">Участники</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'organization:quizzes' %}active{% else %}text-dark{% endif %}" {% if view_name == 'organization:quizzes' %}aria-current="page"{% endif %} href="{% url 'organization:quizzes' pk=request.resolver_match.kwargs.pk %}">Викторины</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'organization:posts' or view_name == 'organization:post_detail' %}active{% else %}text-dark{% endif %}" {% if view_name == 'organization:posts' or view_name == 'organization:post_detail' %}aria-current="page"{% endif %} href="{% url 'organization:posts' pk=request.resolver_match.kwargs.pk %}">Объявления</a>
        </li>
        {% if user_is_admin %}
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'organization:create_quiz' %}active{% else %}text-dark{% endif %}" {% if view_name == 'organization:create_quiz' %}aria-current="page"{% endif %} href="{% url 'organization:create_quiz' pk=request.resolver_match.kwargs.pk %}">Создать викторину</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'organization:create_post' %}active{% else %}text-dark{% endif %}" {% if view_name == 'organization:create_post' %}aria-current="page"{% endif %} href="{% url 'organization:create_post' pk=request.resolver_match.kwargs.pk %}">Создать пост</a>
          </li>
        {% endif %}
      </ul>
    {% endwith %}
    <div class="row flex-lg-row-reverse align-items-center">
      {% block organization_page %}{% endblock organization_page %}
    </div>
  </div>
{% endblock content %}

brainforces/templates/organization/list.html
{% extends "base.html" %}

{% block content %}
  <div class="container col-xxl-9">
    {% include "includes/search_form.html" %}
    {% if organizations %}
      {% for organization in organizations %}
        <div class="col">
          <div class="card shadow-sm mb-2">
            <div class="card-body">
              <h2 class="display-6 fw-bold">{{ organization.name }}</h2>
              {{ organization.description|safe }}
              <a href="{{ organization.get_absolute_url }}" class="btn btn-primary">Смотреть</a>
            </div>
          </div>
        </div>
      {% endfor %}
      {% include "includes/pagination.html" %}
    {% else %}
      {% include "includes/empty.html" %}
    {% endif %}
  </div>
{% endblock content %}

brainforces/templates/organization/post_comments.html
{% extends "organization/detail.html" %}

{% load static %}

{% block organization_page %}
  <div class="col-12">
    <div class="card shadow-sm mb-2">
      <div class="card-body">
        <h2 class="display-6 fw-bold">{{ post.name }}</h2>
        {{ post.text|safe }}
        <div class="d-flex justify-content-between">
          {% include "includes/like_block.html" %}
          {% include "includes/total_views_block.html" %}
        </div>
      </div>
    </div>
  </div>
  <h2 class="display-7 fw-bold">Комментарии</h2>
  {% if request.user.is_authenticated %}
    <form method="post" class="d-flex mb-3">
      {% csrf_token %}
      <input class="form-control me-2" type="textarea" placeholder="Введите комментарий" name="comment_text" />
      <button class="btn btn-primary" type="submit">Готово</button>
    </form>
  {% else %}
    <div><a href="{% url 'users:login' %}">Войдите</a>, чтобы оставить комментарий</div>
  {% endif %}
  {% for comment in comments %}
    <div class="col-12">
      <div class="card shadow-sm mb-2">
        <div class="card-body">
          <span class="fw-bold">{{ comment.user.username }}</span><br/>
          {{ comment.text }}
        </div>
      </div>
    </div>
  {% endfor %}
  <div class="col-12">
    {% include "includes/pagination.html" %}
  </div>
  <script src="{% static 'js/cookie.min.js' %}"></script>
  <script>
    const unliked_src = '/static/img/unliked.svg';
    const liked_src = '/static/img/liked.svg';
  </script>
  <script src="{% static 'js/like_process.js' %}"></script>
{% endblock organization_page %}

brainforces/templates/organization/posts.html
{% extends "organization/detail.html" %}

{% load static %}

{% block organization_page %}
  {% if posts %}
    {% for post in posts %}
      <div class="col-12">
        <div class="card shadow-sm mb-2">
          <div class="card-body">
            <h2 class="display-6 fw-bold">{{ post.name }}</h2>
            {{ post.text|safe }}
            <div class="d-flex justify-content-between">
              {% include "includes/like_block.html" %}
            </div>
            <a href="{% url 'organization:post_detail' pk=post.posted_by.pk post_pk=post.pk %}" class="btn btn-primary mt-2">Смотреть</a>
          </div>
        </div>
      </div>
    {% endfor %}
    {% include "includes/pagination.html" %}
  {% else %}
    {% include "includes/empty.html" %}
  {% endif %}
  <script src="{% static 'js/cookie.min.js' %}"></script>
  <script>
    const unliked_src = '/static/img/unliked.svg';
    const liked_src = '/static/img/liked.svg';
  </script>
  <script src="{% static 'js/like_process.js' %}"></script>
{% endblock organization_page %}

brainforces/templates/organization/profile.html
{% extends "organization/detail.html" %}

{% block organization_page %}
  {{ organization.description|safe }}
  {% if is_group_member == 1 %}
    <a href="{% url 'organization:delete_user' pk=request.resolver_match.kwargs.pk user_pk=request.user.pk %}" class="nav-link p-2">
      <button class="btn btn-danger">Покинуть организацию</button>
    </a>
  {% else %}
    <a href="{% url 'organization:join' pk=request.resolver_match.kwargs.pk %}" class="nav-link p-2">
      <button class="btn btn-primary">Вступить в организацию</button>
    </a>
  {% endif %}
  
{% endblock organization_page %}

brainforces/templates/organization/quizzes.html
{% extends "organization/detail.html" %}

{% block organization_page %}
  {% if quizzes %}
    {% for quiz in quizzes %}
      <div class="col-12">
        <div class="card shadow-sm mb-2">
          <div class="card-body">
            {% include "includes/quiz_detail.html" %}
          </div>
        </div>
      </div>
    {% endfor %}
    {% include "includes/pagination.html" %}
  {% else %}
    {% include "includes/empty.html" %}
  {% endif %}
{% endblock organization_page %}

brainforces/templates/organization/users.html
{% extends "organization/detail.html" %}

{% load widget_tweaks %}

{% block organization_page %}
  {{ context }}
  {% if user_is_admin %}
    <form method="post" class="mb-2">
      {% csrf_token %}
      {% for error in form.errors %}
        <div class="alert alert-danger" role="alert">
          {{ error|safe }}
        </div>
      {% endfor %}
      <div class="gap-2 col-12 d-flex justify-content-between col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <div class="col-md-9 col-6">
          {% render_field form.username class="form-control" placeholder=form.username.help_text %}
        </div>
        <button type="submit" class="btn btn-primary col-md-3 col-6">Пригласить</button>
      </div>
      {% for error in form.username.errors %}
        <div class="alert alert-danger" role="alert">
          {{ error|safe }}
        </div>
      {% endfor %}
    </form>
  {% endif %}
  {% if users %}
    <div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">№</th>
            <th scope="col">Участник</th>
            <th scope="col">Роль</th>
            {% if user_is_admin %}
              <th scope="col">Действие</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for user in users %}
            <tr>
              <td>{{ forloop.counter }}</td>
              <td><a class="nav-link" href="{{ user.user.get_absolute_url }}">{{ user.user.username }}</a></td>
              <td>{{ user.get_role_display }}</td>
              {% if user_is_admin %}
                <td>
                  {% if user.user.id != request.user.id %}
                    {% if user.role < organization_to_user.role %}
                      {% if user.role == 2 or user.role == 1 %}
                        <a href="{% url 'organization:delete_user' pk=request.resolver_match.kwargs.pk user_pk=user.user.pk %}" class="nav-link">Удалить</a>
                      {% endif %}
                      {% if user.role == 2 %}
                        <a href="{% url 'organization:update_user_role' pk=request.resolver_match.kwargs.pk user_pk=user.user.pk new_role=1 %}" class="nav-link">Понизить</a>
                      {% elif user.role == 1 and user.role < organization_to_user.role %}
                        <a href="{% url 'organization:update_user_role' pk=request.resolver_match.kwargs.pk user_pk=user.user.pk new_role=2 %}" class="nav-link">Повысить</a>
                      {% endif %}
                    {% endif %}
                  {% else %}
                    <a href="{% url 'organization:delete_user' pk=request.resolver_match.kwargs.pk user_pk=request.user.pk %}" class="nav-link">Выйти</a>
                  {% endif %}
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% include "includes/pagination.html" %}
  {% else %}
    {% include "includes/empty.html" %}
  {% endif %}
{% endblock organization_page %}